steps:

- id: 'configure git for ssh access'
  name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_github
    chmod 600 /root/.ssh/id_github
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_github
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: 'Terragrunt Init'
  name: 'gcr.io/${PROJECT_ID}/terragrunt'
  args: ['run-all', 'init']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: 'Get Approved Plan'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/github-terraform/plan/$_DIR/$_PLAN_FILE', '$_DIR/$_PLAN_FILE']

- id: 'Terraform Apply'
  name: 'gcr.io/${PROJECT_ID}/terragrunt'
  entrypoint: 'bash'
  secretEnv: ['GITHUB_TOKEN']
  args:
  - '-c'
  - |
    echo $_COMMIT_MESSAGE
    echo $_DIR
    echo ${$_COMMIT_MESSAGE%%-*}
    echo $_DIR
    cd $_DIR
    pwd
    ls
    terragrunt -version 
    terraform version
    terraform apply -input=false -auto-approve $_PLAN_FILE
    ls

availableSecrets:
  secretManager:
  - versionName: projects/tf-cloudbuild-ed58/secrets/github-terraform-modules-repo/versions/latest
    env: 'SSH_KEY'
  - versionName: projects/tf-cloudbuild-ed58/secrets/appcode-github-token/versions/latest
    env: 'GITHUB_TOKEN'

