steps:
- name: 'gcr.io/cloud-builders/git'
  id: Environment
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
      ./wrapper.sh $PROJECT_ID $BUILD_ID $COMMIT_SHA $REVISION_ID $SHORT_SHA $REPO_NAME $BRANCH_NAME $TAG_NAME $_HEAD_BRANCH $_BASE_BRANCH $_HEAD_REPO_URL $_PR_NUMBER $_COMMIT_ADDITIONS $_COMMIT_DATE $_COMMIT_MESSAGE $_COMMIT_URL $_COMMIT_USER $_COMMITS $_IS_COLLABORATOR $_LANGUAGE $_MERGE_TIME $_OWNER $_PERM_LEVEL $_PULL_REQUEST_BODY $_PULL_REQUEST_ID $_PULL_REQUEST_TITLE $_PUSH_NAME $_URL $_USERNAME
