steps:
- name: 'gcr.io/${PROJECT_ID}/terragrunt'
  args: ['run-all', 'init']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     sudo apt-get install tree && \
     tree
