steps:
- name: 'gcr.io/cloud-builders/git'
  id: Environment
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
      ./wrapper.sh $PROJECT_ID $BUILD_ID $COMMIT_SHA $REVISION_ID $SHORT_SHA $REPO_NAME $BRANCH_NAME $TAG_NAME $_HEAD_BRANCH $_BASE_BRANCH $_HEAD_REPO_URL $_PR_NUMBER  
