#!/bin/bash

echo "PROJECT_ID = $1"
echo "BUILD_ID = $2"
echo "COMMIT_SHA = $3"
echo "REVISION_ID = $4"
echo "SHORT_SHA = $5"
echo "REPO_NAME = $6"
echo "BRANCH_NAME = $7"
echo "TAG_NAME = $8"
echo "_HEAD_BRANCH = $9"
echo "_BASE_BRANCH = ${10}"
echo "_HEAD_REPO_URL = ${11}"
echo "_PR_NUMBER = ${12}"

echo "_COMMIT_ADDITIONS = ${13}"
echo "_COMMIT_DATE = ${14}"
echo "_COMMIT_MESSAGE = ${15}"
echo "_COMMIT_URL = ${16}"
echo "_COMMIT_USER = ${17}"
echo "_COMMITS = ${18}"
echo "_IS_COLLABORATOR = ${19}"
echo "_LANGUAGE = ${20}"
echo "_MERGE_TIME = ${21}"
echo "_OWNER = ${22}"
echo "_PERM_LEVEL = ${23}"
echo "_PULL_REQUEST_BODY = ${24}"
echo "_PULL_REQUEST_ID = ${25}"
echo "_PULL_REQUEST_TITLE = ${26}"
echo "_PUSH_NAME = ${27}"
echo "_URL = ${28}"
echo "_USERNAME = ${29}"

#echo " = ${}"

